export const quizList = [
  { id: 1, title: 'A a', source: require('./images/1_A.jpg') },
  { id: 2, title: 'B b', source: require('./images/2_B.jpg') },
  { id: 3, title: 'C c', source: require('./images/3_C.jpg') },
  { id: 4, title: 'D d', source: require('./images/4_D.jpg') },
  { id: 5, title: 'E e', source: require('./images/5_E.jpg') },
  { id: 6, title: 'F f', source: require('./images/6_F.jpg') },
  { id: 7, title: 'G g', source: require('./images/7_G.jpg') },
  { id: 8, title: 'H h', source: require('./images/9_H.jpg') },
  { id: 9, title: 'I i', source: require('./images/10_I.jpg') },
  { id: 10, title: 'J j', source: require('./images/11_J.jpg') },
  { id: 11, title: 'K k', source: require('./images/12_K.jpg') },
  { id: 12, title: 'L l', source: require('./images/13_L.jpg') },
  { id: 13, title: 'M m', source: require('./images/14_M.jpg') },
  { id: 14, title: 'N n', source: require('./images/15_N.jpg') },
  { id: 15, title: 'O o', source: require('./images/16_O.jpg') },
  { id: 16, title: 'P p', source: require('./images/17_P.jpg') },
  { id: 17, title: 'Q q', source: require('./images/18_Q.jpg') },
  { id: 18, title: 'R r', source: require('./images/19_R.jpg') },
  { id: 19, title: 'S s', source: require('./images/20_S.jpg') },
  { id: 20, title: 'T t', source: require('./images/21_T.jpg') },
  { id: 21, title: 'U u', source: require('./images/22_U.jpg') },
  { id: 22, title: 'V v', source: require('./images/21_V.jpg') },
  { id: 23, title: 'W w', source: require('./images/22_W.jpg') },
  { id: 24, title: 'X x', source: require('./images/23_X.jpg') },
  { id: 25, title: 'Y y', source: require('./images/24_Y.jpg') },
  { id: 26, title: 'Z z', source: require('./images/25_Z.jpg') }
]