// export const quizList = [
//   { id: 1, title: 'A a', source: require('./images/1_A.jpg') },
//   { id: 2, title: 'B b', source: require('./images/2_B.jpg') },
//   { id: 3, title: 'C c', source: require('./images/3_C.jpg') },
//   { id: 4, title: 'D d', source: require('./images/4_D.jpg') },
//   { id: 5, title: 'E e', source: require('./images/5_E.jpg') },
//   { id: 6, title: 'F f', source: require('./images/6_F.jpg') },
//   { id: 7, title: 'G g', source: require('./images/7_G.jpg') },
//   { id: 8, title: 'H h', source: require('./images/9_H.jpg') },
//   { id: 9, title: 'I i', source: require('./images/10_I.jpg') },
//   { id: 10, title: 'J j', source: require('./images/11_J.jpg') },
//   { id: 11, title: 'K k', source: require('./images/12_K.jpg') },
//   { id: 12, title: 'L l', source: require('./images/13_L.jpg') },
//   { id: 13, title: 'M m', source: require('./images/14_M.jpg') },
//   { id: 14, title: 'N n', source: require('./images/15_N.jpg') },
//   { id: 15, title: 'O o', source: require('./images/16_O.jpg') },
//   { id: 16, title: 'P p', source: require('./images/17_P.jpg') },
//   { id: 17, title: 'Q q', source: require('./images/18_Q.jpg') },
//   { id: 18, title: 'R r', source: require('./images/19_R.jpg') },
//   { id: 19, title: 'S s', source: require('./images/20_S.jpg') },
//   { id: 20, title: 'T t', source: require('./images/21_T.jpg') },
//   { id: 21, title: 'U u', source: require('./images/22_U.jpg') },
//   { id: 22, title: 'V v', source: require('./images/21_V.jpg') },
//   { id: 23, title: 'W w', source: require('./images/22_W.jpg') },
//   { id: 24, title: 'X x', source: require('./images/23_X.jpg') },
//   { id: 25, title: 'Y y', source: require('./images/24_Y.jpg') },
//   { id: 26, title: 'Z z', source: require('./images/25_Z.jpg') }
// ]

export const quizList = [
  { id: 1, title: 'अ', source: require('../images/swar/1_a.png') },
  { id: 2, title: 'आ', source: require('../images/swar/2_aa.png') },
  { id: 3, title: 'इ', source: require('../images/swar/3_i.png') },
  { id: 4, title: 'ई', source: require('../images/swar/4_ii.png') },
  { id: 5, title: 'उ', source: require('../images/swar/5_u.png') },
  { id: 6, title: 'ऊ', source: require('../images/swar/6_uu.png') },
  { id: 7, title: 'ए', source: require('../images/swar/7_e.png') },
  { id: 8, title: 'ऐ', source: require('../images/swar/8_ai.png') },
  { id: 9, title: 'ओ', source: require('../images/swar/9_o.png') },
  { id: 10, title: 'औ', source: require('../images/swar/10_au.png') }
]

// export const vyanjan = [
//   { id: 1, title: 'क', source: require('./images/vyanjan/1_k.png') },
//   { id: 2, title: 'ख', source: require('./images/vyanjan/2_kh.png') },
//   { id: 3, title: 'ग', source: require('./images/vyanjan/3_g.png') },
//   { id: 4, title: 'घ', source: require('./images/vyanjan/4_gh.png') },
//   { id: 5, title: 'च', source: require('./images/vyanjan/5_ch.png') },
//   { id: 6, title: 'छ', source: require('./images/vyanjan/6_chh.png') },
//   { id: 7, title: 'ज', source: require('./images/vyanjan/7_j.png') },
//   { id: 8, title: 'झ', source: require('./images/vyanjan/8_jh.png') },
//   { id: 9, title: 'ट', source: require('./images/vyanjan/9_t.png') },
//   { id: 10, title: 'ठ', source: require('./images/vyanjan/10_th.png') },
//   { id: 11, title: 'ड', source: require('./images/vyanjan/11_d.png') },
//   { id: 12, title: 'ढ', source: require('./images/vyanjan/12_dh.png') },
//   { id: 13, title: 'ण', source: require('./images/vyanjan/13_n.png') },
//   { id: 14, title: 'त', source: require('./images/vyanjan/14_t.png') },
//   { id: 15, title: 'थ', source: require('./images/vyanjan/15_th.png') },
//   { id: 16, title: 'द', source: require('./images/vyanjan/16_d.png') },
//   { id: 17, title: 'ध', source: require('./images/vyanjan/17_dh.png') },
//   { id: 18, title: 'न', source: require('./images/vyanjan/18_n.png') },
//   { id: 19, title: 'प', source: require('./images/vyanjan/19_p.png') },
//   { id: 20, title: 'फ', source: require('./images/vyanjan/20_ph.png') },
//   { id: 21, title: 'ब', source: require('./images/vyanjan/21_b.png') },
//   { id: 22, title: 'भ', source: require('./images/vyanjan/22_bh.png') },
//   { id: 23, title: 'म', source: require('./images/vyanjan/23_m.png') },
//   { id: 24, title: 'य', source: require('./images/vyanjan/24_y.png') },
//   { id: 25, title: 'र', source: require('./images/vyanjan/25_r.png') },
//   { id: 26, title: 'ल', source: require('./images/vyanjan/26_l.png') },
//   { id: 27, title: 'व', source: require('./images/vyanjan/28_v.png') },
//   { id: 28, title: 'श', source: require('./images/vyanjan/29_sh.png') },
//   { id: 29, title: 'स', source: require('./images/vyanjan/30_s.png') },
//   { id: 30, title: 'ह', source: require('./images/vyanjan/31_h.png') },
//   { id: 31, title: 'ळ', source: require('./images/vyanjan/32_l.png') },
//   { id: 32, title: 'क्ष', source: require('./images/vyanjan/33_ksh.png') },
//   { id: 33, title: 'ज्ञ', source: require('./images/vyanjan/34_dny.png') }
// ]